### ISSUE TITLE
Add styled footer 

### ISSUE THREAD

**Issue by fridaland** [fridaland/InTheFight#19]
### Global Footer 

Create and style footer.

Footer will include media link icons (you can find these in the project) on the right and the In The Fight logo on the right. 

Footer specs:
```

position: absolute;
width: 1280px;
height: 259px;

/* Cream */
background: #FAF5EB
```
Font/Icon color
```
color:  #2C358F

```

- In The Fight logo will navigate to home
- IG icon to [instagram account](https://www.google.com/url?q=https%3A%2F%2Fwww.instagram.com%2Finthefightnbk%2F&sa=D&sntz=1&usg=AFQjCNH0p61yXGl9bMeue6Bs-rRKiiv4yQ)
- twitter icon to [twitter account](https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2Finthefightnbk&sa=D&sntz=1&usg=AFQjCNEb00NfVsQEv6wvlOqtg-_5gZdMSA)
- facebook icon to [facebook account](https://www.google.com/url?q=https%3A%2F%2Fwww.facebook.com%2Fgroups%2Finthefightnbk&sa=D&sntz=1&usg=AFQjCNFvmpPaYNcfAtgoFCyzpbJUZtdycg)
- medium icon to [medium account](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40inthefightnbk&sa=D&sntz=1&usg=AFQjCNE1S6MNSMWyoBVw-uZPVpnkbnaluQ)

![Screen Shot 2020-10-20 at 8 19 25 AM](https://user-images.githubusercontent.com/40510669/96591760-38694f80-12ad-11eb-9e8b-19dbff5b2eff.png)

**Comment by Mamoanwar97** [comment]
Can you assign it to me? I can make it for you, I have a published gatsby website [https://mymelior.com/](https://mymelior.com/)

**Comment by Shreelaxmi-M** [comment]
Even I want to try this,can you assign it to me?

**Comment by poleselfg** [comment]
Hello! i can help with this!

**Comment by Johnisaig** [comment]
Can I work on this?

**Comment by fridaland** [comment]
Thanks all - @mamoanwar97  assigned it to you as you were the first to have a comment! Let me know if you run into any issues!

**Comment by fridaland** [comment]
@shree-create @poleselfg @Johnisaig thanks so much for your interest!  I'll be adding more good first issues very soon, feel free to check them out!

**Comment by Mamoanwar97** [comment]
@fridaland  While I am trying to start the project, it gives me this error .. any idea about it?
![image](https://user-images.githubusercontent.com/36894846/96900416-5b088d80-1492-11eb-950d-354b7d6b5a2d.png)

**Comment by fridaland** [comment]
@mamoanwar97  Can you pull the latest master? It should have a `.env.development` file added to take care of those contentful env variables the build is looking for.
Check out [this commit](https://github.com/fridaland/InTheFight/commit/16ad83de0101331f66d195b8a1db3f3e9d50b4b9)

**Comment by Mamoanwar97** [comment]
yes, it is working fine now, thanks

**Comment by Mamoanwar97** [comment]
is it showing like this right? i am just asking to be sure that everything is working fine before I start making the footer
![image](https://user-images.githubusercontent.com/36894846/96923019-f7418d00-14b0-11eb-9645-21d0b887ec08.png)

**Comment by fridaland** [comment]
Yep, you got it! There aren't really many styles in place, you should be good to go @mamoanwar97!

**Comment by Mamoanwar97** [comment]
do you have these social icons as svg or png?

**Comment by fridaland** [comment]
@mamoanwar97  I [added some png images](https://github.com/fridaland/InTheFight/commit/2346a7213b5e7998b635972098b0a732b83d9756) under `images/logos`. You should be able to find them there. :)

**Comment by fridaland** [comment]
Closing with #28
