### ISSUE TITLE
Create new Blogs route + page

### ISSUE THREAD

**Issue by fridaland** [fridaland/InTheFight#20]
### Blogs Page

Create a new route element for Blogs.
This can currently serve a blank page with the title "Blogs".
We should ensure a Blog link is added to the NavBar.

**Comment by kud04rk** [comment]
Added blogs page to the website PR #24

**Comment by connerdodge** [comment]
@smsriharsha There is already a PR (#23) raised for this issue

**Comment by fridaland** [comment]
Resolved with #23
