### ISSUE TITLE
Style Homepage Headline and statement

### ISSUE THREAD

**Issue by fridaland** [fridaland/InTheFight#21]
## Homepage Headline and statement

Currently there is a title and brief description in the homepage.
These two elements should be styled to match the below image. 

Css specs for Headline title:
```
font-weight: bold;
font-size: 48px;
color: #2C358F;
```

Css specs for paragraph description:
```
font-size: 20px;
color: #000000;
```

![Screen Shot 2020-10-22 at 10 42 51 AM](https://user-images.githubusercontent.com/40510669/96896691-6dafa200-1453-11eb-8cc6-c091f6de5673.png)

**Comment by kud04rk** [comment]
I have added the mentioned styles in PR #24

**Comment by connerdodge** [comment]
@smsriharsha There is already a PR raised for this issue

**Comment by fridaland** [comment]
Closing with #22
