### ISSUE TITLE
Style Navbar for all pages except homepage

### ISSUE THREAD

**Issue by fridaland** [fridaland/InTheFight#27]
Style NavBar for all pages except homepage

### Style NavBar

This styled NavBar will appear in every page _except the homepage_

Style specs:
```
height: 76px;
background: #FAF5EB;

Logo text:
font-family: DIN Condensed;
font-weight: bold;
font-size: 48px;
text-transform: uppercase;
color: #2C358F;

Nav Items:
font-family: URW DIN;
font-weight: bold;
font-size: 16px;
text-transform: uppercase;
color: #2C358F;
```

<img width="699" alt="Screen Shot 2020-10-23 at 11 45 19 AM" src="https://user-images.githubusercontent.com/40510669/97031238-92744a00-1525-11eb-8b2f-5f9d36cdb9f7.png">

**Comment by hn4733** [comment]
Please check out my PR for this task. I've also optimised the header for mobile view on subpages as well.
