### ISSUE TITLE
Configure eslint 

### ISSUE THREAD

**Issue by fridaland** [fridaland/InTheFight#31]
### Configure eslint 

Add eslint package to keep code clean and consistent. 
 
Helpful resource: https://www.gatsbyjs.com/plugins/gatsby-plugin-eslint/

**Comment by JoelLau** [comment]
hi @fridaland, can I take this up as part of hacktoberfest?

**Comment by fridaland** [comment]
@JoelLau  It's yours!

**Comment by fridaland** [comment]
Resolved by #33
